// <auto-generated />
namespace T1809E.SEM3.P102_Team05.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addAttrProducts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addAttrProducts));
        
        string IMigrationMetadata.Id
        {
            get { return "202004270152471_addAttrProducts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
